name       : python-css-parser
version    : 1.0.9
release    : 9
source     :
    - https://pypi.python.org/packages/source/c/css-parser/css-parser-1.0.9.tar.gz : 196db822cef22745af6a58d180cf8206949ced58b48f5f3ee98f1de1627495bb
homepage   : https://github.com/ebook-utils/css-parser
license    : LGPL-3.0-or-later
component  : programming.python
summary    : A CSS Cascading Style Sheets library for Python
description: |
    CSS related utilities (parsing, serialization, etc) for python.
builddeps  :
    - python-pytest # check
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
