name       : python-css-parser
version    : 1.0.4
release    : 1
source     :
    - https://pypi.python.org/packages/source/c/css-parser/css-parser-1.0.4.tar.gz : c7ab355512ae51334ba6791a7e4d553f87bef17ba2026f1cc9bf3b17a7779d44
license    : LGPL-3.0-or-later
component  : programming.python
summary    : A CSS Cascading Style Sheets library for Python
description: |
    CSS related utilities (parsing, serialization, etc) for python.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
