name       : python-css-parser
version    : 1.0.8
release    : 8
source     :
    - https://pypi.python.org/packages/source/c/css-parser/css-parser-1.0.8.tar.gz : 994d6a0115a8f4e2b6648e2b12733036d05fa164278aa234630c9f03e52c8c80
homepage   : https://github.com/ebook-utils/css-parser
license    : LGPL-3.0-or-later
component  : programming.python
summary    : A CSS Cascading Style Sheets library for Python
description: |
    CSS related utilities (parsing, serialization, etc) for python.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
